Fix invalid Web IDL
w3c/json-ld-framing pull request #135
Opened 2022-08-29 09:53 UTC by tidoust

The JSON-LD Framing API specification extends interfaces of the JSON-LD API but does not use the `partial` extension keyword, meaning that interfaces from both specs cannot be automatically merged into one.

The JSON-LD Framing API specification also re-defines interfaces that are already defined in the JSON-LD API for no apparent reason, which is bad practice as it creates two normative definitions of the same object.

This update makes the following changes to drop duplicate definitions and improve cross-reference links between the JSON-LD Framing API and the JSON-LD API:
- Dropped duplicate definition of `JsonLd` interface
- Defined `JsonLdProcessor` as `partial` (and dropped `constructor` member since it is already defined in the JSON-LD API)
- Dropped duplicate definitions of `JsonLdRecord` and `JsonLdInput`
- Defined `JsonLdOptions` as `partial` (and dropped `ordered` since it is already defined in the JSON-LD API)
- Replaced `data-cite` links with `{{xx}}` links where possible
- Dropped self-reference from `xref` ReSpec config array (useless, local definitions are always available)

2022-08-29 15:15 UTC, gkellogg commented
Thanks you. During development, effective guidance on the use of WebIDL was hard to come by. With some more administrivia, we can update the ED. It seems that we’d need to publishe an edited recommendation to fix the problem in a Xref, though.

2022-08-29 17:55 UTC, gkellogg requested changes
Please add the following to the end of the list for "Changes since Recommendation of 16 July 2020":

```
<li>Updated
  <a href="#jsonldprocessor" class="sectionRef"></a> and
  <a href="#jsonldoptions" class="sectionRef"></a>
  to correct invalid WebIDL.
  Also updated internal references to use appropriate reference syntax.
  This is in response to <a href="https://github.com/w3c/json-ld-framing/issues/136">Issue 136</a>.
</li>
```

2022-08-30 14:49 UTC, gkellogg approved these changes

2022-08-30 15:25 UTC, pchampin approved these changes

2022-08-30 15:36 UTC, merged